// Code generated by goctl. DO NOT EDIT.
package types

type GetNonceResp struct {
	Nonce string `json:"nonce"`
}

type LoginReq struct {
	UAddress   string `json:"uAddress"`            //用户钱包地址
	InviteCode string `json:"inviteCode,optional"` //邀请码
	ChainId    int64  `json:"chainId"`             //链Id
	Timestamp  int64  `json:"timestamp"`           //时间戳
	Signature  string `json:"signature"`           //钱包签名
	Nonce      string `json:"nonce"`               //钱包签名随机串， getNonce()接口获取
}

type LoginResp struct {
	Token string `json:"token"`
}

type AdminLoginReq struct {
	UAddress  string `json:"uAddress"`
	ChainId   int64  `json:"chainId"`
	Timestamp int64  `json:"timestamp"`
	Signature string `json:"signature"`
	Nonce     string `json:"nonce"`
}

type AdminLoginResp struct {
	Token string `json:"token"`
	Role  string `json:"role"`
}

type PersonInfoReq struct {
}

type PersonInfoResp struct {
	UAddress      string `json:"u_address"`      //钱包地址
	ParentAddress string `json:"parent_address"` //邀请者地址
	InviteCode    string `json:"invite_code"`    //邀请码
	CreateAt      int64  `json:"created_at"`     //注册时间
}

type InviteReq struct {
	UAddress string `json:"uAddress"`
}

type InviteResp struct {
	Tribe       int `json:"tribe"`
	Recommender int `json:"recommender"`
}

type GetInviterResp struct {
	PAddress    string `json:"pAddress"`
	PInviteCode string `json:"pInviteCode"`
	InviteCode  string `json:"inviteCode"`
}

type InviteCodeReq struct {
	InviteCode string `json:"inviteCode"`
}

type InviteCountResp struct {
	Count       int64 `json:"count"`
	ActiveCount int64 `json:"active_count"`
	TeamLevel   int64 `json:"team_level"`
}

type UserAddressResgiterReq struct {
	UAddress string `json:"uAddress"`
}

type UserAddressResgiterResp struct {
	UAddress   string `json:"uAddress"`
	IsRegister bool   `json:"isRegister"`
}

type InviteUserReq struct {
	PageNo   int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type InviteUserResp struct {
	List     []UserInviteItem `json:"list"`
	PageNo   int64            `json:"page"`
	PageSize int64            `json:"page_size"`
	Total    int64            `json:"total"`
}

type UserInviteItem struct {
	ID        int64  `json:"id"`
	UAddress  string `json:"u_address"`
	CreatedAt int64  `json:"created_at"`
}

type UserItem struct {
	Id            int64   `json:"id"`
	UAddress      string  `json:"u_address"`
	ParentAddress string  `json:"parent_address"`
	Amount        float64 `json:"amount"`
	InviteCode    string  `json:"invite_code"`
	Path          string  `json:"path"`
	CreateAt      string  `json:"created_at"`
}

type WalletLogListReq struct {
	TypeId   int32 `json:"type_id"`         //1-佣金记录， 2-回报记录
	Page     int64 `json:"page"`            // 页码
	PageSize int64 `json:"page_size"`       // 每页数量
	TargetId int64 `json:"target_id"`       //对应的业务ID
	STime    int64 `json:"s_time,optional"` //开始时间
	ETime    int64 `json:"e_time,optional"` //结束时间
}

type WalletLogListItem struct {
	CreatedAt     int64   `json:"createdAt"`      //创建时间
	Amount        float64 `json:"amount"`         //变动金额
	TargetAddress string  `json:"target_address"` //金额变动来源地址
	UAddress      string  `json:"u_address"`      //金额变动地址
}

type WalletLogListResp struct {
	List     []WalletLogListItem `json:"list"`
	Page     int64               `json:"page"`      // 页码
	PageSize int64               `json:"page_size"` // 每页数量
	Total    int64               `json:"total"`     // 总数
}

type InviteCodeResp struct {
}

type PackageProjectChildListItem struct {
	Id   int64  `json:"id"`   //子项目ID
	Name string `json:"name"` //子项目名字
	Icon string `json:"icon"`
}

type GetPackageProjectList struct {
	Id    int64                         `json:"id"`    //项目ID
	Name  string                        `json:"name"`  //项目名字
	Price float64                       `json:"price"` //价格
	Month int64                         `json:"month"` //服务周期
	List  []PackageProjectChildListItem `json:"list"`
}

type GetPackageProjectListReq struct {
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
}

type GetPackageProjectListResp struct {
	List     []GetPackageProjectList `json:"list"`
	Page     int32                   `json:"page"`      // 页码
	PageSize int32                   `json:"page_size"` // 每页数量
	Total    int64                   `json:"total"`     // 总数
}

type BuyPackageProjectReq struct {
	Id int64 `json:"id"`
}

type BuyPackageProjectResp struct {
	OrderId int64   `json:"order_id"`
	Amount  float64 `json:"Amount"`
	Sign    string  `json:"sign"`
}

type GetLinkProjectList struct {
	Id       int64   `json:"id"`        //项目ID
	Name     string  `json:"name"`      //项目名字
	Price    float64 `json:"price"`     //价格
	DropTime int64   `json:"drop_time"` //法币时间
	Icon     string  `json:"icon"`
}

type GetLinkProjectListReq struct {
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
}

type GetLinkProjectListResp struct {
	List     []GetLinkProjectList `json:"list"`
	Page     int32                `json:"page"`      // 页码
	PageSize int32                `json:"page_size"` // 每页数量
	Total    int64                `json:"total"`     // 总数
}

type BuyLinkProjectReq struct {
	Id int64 `json:"id"`
}

type BuyLinkProjectResp struct {
	OrderId int64   `json:"order_id"`
	Amount  float64 `json:"Amount"`
	Sign    string  `json:"sign"`
}

type GetOrderInfoReq struct {
}

type GetOrderInfoResp struct {
	TotalBuyAmount         float64 `json:"total_buy_amount"`         //累计投资金额
	LinkEarnings           float64 `json:"link_earnings"`            //全链空投收益
	ReceivePackageEarnings float64 `json:"receive_package_earnings"` //已发放私募空投
	WaitPackageEarnings    float64 `json:"wait_package_earnings"`    //待领取的私募空投
	CommissionEarnings     float64 `json:"commission_earnings"`      //佣金奖励
	AIOrderRunningNumber   float64 `json:"ai_earnings"`              //ai算力已购买未到期的订单数量
}

type GetPackageOrderListReq struct {
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
}

type GetPackageOrderListItem struct {
	Id              int64   `json:"id"`
	Created_at      int64   `json:"created_at"`        //投资时间
	Amount          float64 `json:"amount"`            //投资额度
	Month           int32   `json:"month"`             //服务周期
	LeftDay         int32   `json:"left_day"`          //剩余回报时间
	SendEarnings    float64 `json:"send_earnings"`     //已回报金额
	MaxEarningsRate float64 `json:"max_earnings_rate"` //最高回报率
}

type GetPackageOrderListResp struct {
	List     []GetPackageOrderListItem `json:"list"`
	Page     int32                     `json:"page"`      // 页码
	PageSize int32                     `json:"page_size"` // 每页数量
	Total    int64                     `json:"total"`     // 总数
}

type GetLinkOrderListReq struct {
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
	Ststus   int32 `json:"ststus"`    //
}

type GetLinkOrderListItem struct {
	CreatedAt int64   `json:"created_at"` //投资时间
	Name      string  `json:"name"`       //项目名字
	BuyNumber int32   `json:"buy_number"` //认购数量
	BuyAmount float64 `json:"buy_amount"` //认购金额
	DropTime  int64   `json:"drop_time"`  //发币时间
	Status    int32   `json:"status"`     //状态 0-全部 1-待发放 2-已发放待领取 3-已领取
}

type GetLinkOrderListResp struct {
	List     []GetLinkOrderListItem `json:"list"`
	Page     int32                  `json:"page"`      // 页码
	PageSize int32                  `json:"page_size"` // 每页数量
	Total    int64                  `json:"total"`     // 总数
}

type ApplyLinkEarningsReq struct {
	Id      int64   `json:"id"`
	Address string  `json:"address"`
	Amount  float64 `json:"amount"`
}

type ApplyLinkEarningsResp struct {
}

type GetApplyLinkLogListReq struct {
	Id       int64 `json:"id"`
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
	Status   int32 `json:"status"`    //'1 未发放 2 已发放待领取 3 已领取',
}

type GetApplyLinkLogListItem struct {
	CreatedAt int64   `json:"createdAt"`
	UAddress  string  `json:"uAddress"`
	Amount    float64 `json:"amount"`
}

type GetApplyLinkLogListResp struct {
	List     []GetApplyLinkLogListItem `json:"list"`
	Page     int32                     `json:"page"`      // 页码
	PageSize int32                     `json:"page_size"` // 每页数量
	Total    int64                     `json:"total"`     // 总数
}

type AdminGetLinkProjectListReq struct {
	Page     int32  `json:"page"`            // 页码
	PageSize int32  `json:"page_size"`       // 每页数量
	STime    int64  `json:"s_time,optional"` //开始时间
	ETime    int64  `json:"e_time,optional"` //结束时间
	Name     string `json:"name,optional"`   //模糊查询
}

type GetLinkProjectListItem struct {
	Id          int64   `json:"id"`            //序号
	ProjectId   int64   `json:"project_id"`    //项目ID
	Name        string  `json:"name"`          //名字
	Icon        string  `json:"icon"`          //图标
	Price       float64 `json:"price"`         //售价
	DropAmount  float64 `json:"drop_amount"`   //代币数量
	SellEndTime int64   `json:"sell_end_time"` //销售结束时间
	DropTime    int64   `json:"drop_time"`     //发币时间
	CreatedAt   int64   `json:"created_at"`
	Status      int32   `json:"status"` // 1-上架 ，2 下架
}

type AdminGetLinkProjectListResp struct {
	List     []GetLinkProjectListItem `json:"list"`
	Page     int32                    `json:"page"`      // 页码
	PageSize int32                    `json:"page_size"` // 每页数量
	Total    int64                    `json:"total"`     // 总数
}

type AddOrUpdateLinkProjectReq struct {
	Id          int64   `json:"id,optional"`
	ProjectId   int64   `json:"project_id"`
	Price       float64 `json:"price"`           //售价
	DropAmount  float64 `json:"drop_amount"`     //代币数量
	SellEndTime int64   `json:"sell_end_time"`   //销售结束时间
	DropTime    int64   `json:"drop_time"`       //发币时间
	IsDeleted   int32   `json:"is_deleted"`      //1-删除
	Status      int32   `json:"status,optional"` // 1-上架 ，2 下架
}

type AddOrUpdateLinkProjectResp struct {
}

type GetLinkProjectOrderListReq struct {
	Page     int32  `json:"page"`               // 页码
	PageSize int32  `json:"page_size"`          // 每页数量
	STime    int64  `json:"s_time,optional"`    //开始时间
	ETime    int64  `json:"e_time,optional"`    //结束时间
	UAddress string `json:"u_address,optional"` //用户地址
}

type GetLinkProjectOrderListItem struct {
	Id        int64   `json:"id"`         //订单号
	UserId    int64   `json:"user_id"`    //订单号
	Name      string  `json:"name"`       //项目名字
	UAddress  string  `json:"u_address"`  //订单用户
	Amount    float64 `json:"amount"`     //订单金额
	CreatedAt int64   `json:"created_at"` //订单时间
	Status    int32   `json:"status"`     //提币状态 0-全部 1-待发放 2-已发放待领取 3-已领取'
	Icno      string  `json:"icno"`       //base64
}

type GetLinkProjectListOrderResp struct {
	List     []GetLinkProjectOrderListItem `json:"list"`
	Page     int32                         `json:"page"`      // 页码
	PageSize int32                         `json:"page_size"` // 每页数量
	Total    int64                         `json:"total"`     // 总数
}

type GetPackageProjectOrderListReq struct {
	Page     int32  `json:"page"`               // 页码
	PageSize int32  `json:"page_size"`          // 每页数量
	STime    int64  `json:"s_time,optional"`    //开始时间
	ETime    int64  `json:"e_time,optional"`    //结束时间
	UserId   int64  `json:"user_id,optional"`   //用户ID
	UAddress string `json:"u_address,optional"` //用户地址
}

type GetPackageProjectOrderListItem struct {
	Id           int64   `json:"id"`            //订单号
	UserId       int64   `json:"user_id"`       //订单号
	UAddress     string  `json:"u_address"`     //订单用户
	Amount       float64 `json:"amount"`        //订单金额
	BuyMonth     int32   `json:"buy_month"`     //服务周期
	LeftDay      int32   `json:"left_day"`      //剩余回报时间
	SendEarnings float64 `json:"send_earnings"` //已回报金额
	CreatedAt    int64   `json:"created_at"`    //订单时间
}

type GetPackageProjectListOrderResp struct {
	List     []GetPackageProjectOrderListItem `json:"list"`
	Page     int32                            `json:"page"`      // 页码
	PageSize int32                            `json:"page_size"` // 每页数量
	Total    int64                            `json:"total"`     // 总数
}

type DropLinkApplyLinkProjectReq struct {
	Id       int64   `json:"id"`        //订单号
	UAddress string  `json:"u_address"` //订单用户
	Amount   float64 `json:"amount"`    //发放数量
}

type DropApplyLinkProjectResp struct {
}

type DropApplyPackageProjectReq struct {
	Id     int64   `json:"id"`     //订单号
	Amount float64 `json:"amount"` //发放数量
}

type DropApplyPackageProjectResp struct {
}

type DropApplyPackageListProjectReq struct {
	Id       int64 `json:"id"`              //订单号
	Page     int32 `json:"page"`            // 页码
	PageSize int32 `json:"page_size"`       // 每页数量
	STime    int64 `json:"s_time,optional"` //开始时间
	ETime    int64 `json:"e_time,optional"` //结束时间
}

type DropApplyPackageListProjectItem struct {
	Id        int64   `json:"id"`
	UAddress  string  `json:"u_address"`  //订单用户
	Amount    float64 `json:"amount"`     //发放数量
	CreatedAt int64   `json:"created_at"` //发放时间
}

type DropApplyPackageListProjectResp struct {
	List     []DropApplyPackageListProjectItem `json:"list"`
	Page     int32                             `json:"page"`      // 页码
	PageSize int32                             `json:"page_size"` // 每页数量
	Total    int64                             `json:"total"`     // 总数
}

type AdminGetPackageProjectListReq struct {
	Page     int32  `json:"page"`            // 页码
	PageSize int32  `json:"page_size"`       // 每页数量
	STime    int64  `json:"s_time,optional"` //开始时间
	ETime    int64  `json:"e_time,optional"` //结束时间
	Name     string `json:"name,optional"`   //模糊查询
	Status   int32  `json:"status,optional"` //状态 1-上架 2-下架
}

type AdminPackageProjectChildListItem struct {
	Id   int64  `json:"id"`   //子项目ID
	Name string `json:"name"` //子项目名字
	Icon string `json:"icon"` //图标，base64
}

type GetPackageProjectListItem struct {
	Id     int64                              `json:"id"`     //项目ID
	Name   string                             `json:"name"`   //项目名字
	Price  float64                            `json:"price"`  //价格
	Month  int64                              `json:"month"`  //服务周期
	Status int32                              `json:"status"` //状态 1-上架 2-下架
	List   []AdminPackageProjectChildListItem `json:"list"`
}

type AdminGetPackageProjectListResp struct {
	List     []GetPackageProjectListItem `json:"list"`
	Page     int32                       `json:"page"`      // 页码
	PageSize int32                       `json:"page_size"` // 每页数量
	Total    int64                       `json:"total"`     // 总数
}

type AddOrUpdatePackageProjectReq struct {
	ProjectIds []AdminPackageProjectChildListItem `json:"project_ids"`
	Month      int64                              `json:"month"`               //服务周期
	Price      float64                            `json:"price"`               //价格
	Id         int64                              `json:"id,optional"`         //项目ID
	Status     int32                              `json:"status"`              //状态 1-上架 2-下架
	IsDeleted  int                                `json:"is_deleted,optional"` // 1-删除标记
}

type AddOrUpdatePackageProjectResp struct {
}

type GetProjectListReq struct {
	Page     int32  `json:"page"`            // 页码
	PageSize int32  `json:"page_size"`       // 每页数量
	STime    int64  `json:"s_time,optional"` //开始时间
	ETime    int64  `json:"e_time,optional"` //结束时间
	Name     string `json:"name,optional"`   //模糊查询
}

type GetProjectListItem struct {
	Id      int64  `json:"id,optional"`
	Icon    string `json:"icon"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type GetProjectListResp struct {
	List     []GetProjectListItem `json:"list"`
	Page     int32                `json:"page"`      // 页码
	PageSize int32                `json:"page_size"` // 每页数量
	Total    int64                `json:"total"`     // 总数
}

type AddOrUpdateProjectReq struct {
	Id        int64  `json:"id,optional"`
	Icon      string `json:"icon"`                //logo ,base64
	Name      string `json:"name"`                //项目名
	Content   string `json:"content"`             //项目介绍
	IsDeleted int    `json:"is_deleted,optional"` // 1-删除标记
}

type AddOrUpdateProjectResp struct {
}

type GetSettingListReq struct {
	Page     int32 `json:"page"`            // 页码
	PageSize int32 `json:"page_size"`       // 每页数量
	STime    int64 `json:"s_time,optional"` //开始时间
	ETime    int64 `json:"e_time,optional"` //结束时间
}

type GetSettingListItem struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type GetSettingListResp struct {
	List     []GetSettingListItem `json:"list"`
	Page     int32                `json:"page"`      // 页码
	PageSize int32                `json:"page_size"` // 每页数量
	Total    int64                `json:"total"`     // 总数
}

type GetSettingKeyReq struct {
	Key string `json:"key"`
}

type GetSettingKeyResp struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SetSettingKeyReq struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SetSettingKeyResp struct {
}

type GetUserListReq struct {
	Page       int32  `json:"page"`                 // 页码
	PageSize   int32  `json:"page_size"`            // 每页数量
	STime      int64  `json:"s_time,optional"`      //开始时间
	ETime      int64  `json:"e_time,optional"`      //结束时间
	UAddress   string `json:"u_address,optional"`   //用户地址
	PAddress   string `json:"p_address,optional"`   //邀请者地址
	InviteCode string `json:"invite_code,optional"` //邀请码
	Id         int64  `json:"id,optional"`          //用户ID
}

type GetUserListitem struct {
	Id         int64  `json:"id"`          //用户ID
	UAddress   string `json:"u_address"`   //用户地址
	InviteCode string `json:"invite_code"` //邀请码
	CreatedAt  int64  `json:"created_at"`  //创建时间
	PAddress   string `json:"p_address"`   //邀请者地址
}

type GetUserListResp struct {
	List     []GetUserListitem `json:"list"`
	Page     int32             `json:"page"`      // 页码
	PageSize int32             `json:"page_size"` // 每页数量
	Total    int64             `json:"total"`     // 总数
}

type AdminWalletLogListReq struct {
	TypeId   int32  `json:"type_id,optional"` //0-全部，1-佣金记录， 2-回报记录
	Page     int64  `json:"page"`             // 页码
	PageSize int64  `json:"page_size"`        // 每页数量
	UserId   int64  `json:"user_id,optional"`
	UAddress string `json:"u_address,optional"`
	STime    int64  `json:"s_time,optional"` //开始时间
	ETime    int64  `json:"e_time,optional"` //结束时间
}

type AdminWalletLogListItem struct {
	CreatedAt     int64   `json:"createdAt"`      //创建时间
	Amount        float64 `json:"amount"`         //佣金金额
	TargetAddress string  `json:"target_address"` //发送用户
	UAddress      string  `json:"u_address"`      //接收用户
}

type AdminWalletLogListResp struct {
	List     []AdminWalletLogListItem `json:"list"`
	Page     int64                    `json:"page"`      // 页码
	PageSize int64                    `json:"page_size"` // 每页数量
	Total    int64                    `json:"total"`     // 总数
}

type AdminGetAiComputingListItem struct {
	Id                  int64   `json:"id"`    //项目ID
	Name                string  `json:"name"`  //项目名字
	Price               float64 `json:"price"` //价格
	Icon                string  `json:"icon"`
	Content             string  `json:"content"`               //描述
	ServiceMonth        int32   `json:"service_month"`         //有效期
	ComputingPowerUnit  string  `json:"computing_power_unit"`  //算力单位
	ComputingPowerValue int64   `json:"computing_power_value"` //算力值
	CreatedAt           int64   `json:"created_at"`
	Status              int32   `json:"status"` // 1-上架 2-下架
}

type AdminGetAiComputingListReq struct {
	Page     int32  `json:"page"`            // 页码
	PageSize int32  `json:"page_size"`       // 每页数量
	STime    int64  `json:"s_time,optional"` //开始时间
	ETime    int64  `json:"e_time,optional"` //结束时间
	Name     string `json:"name,optional"`   //模糊查询
}

type AdminGetAiComputingListResp struct {
	List     []AdminGetAiComputingListItem `json:"list"`
	Page     int32                         `json:"page"`      // 页码
	PageSize int32                         `json:"page_size"` // 每页数量
	Total    int64                         `json:"total"`     // 总数
}

type AdminAiComputingOrderListReq struct {
	Page     int32  `json:"page"`               // 页码
	PageSize int32  `json:"page_size"`          // 每页数量
	STime    int64  `json:"s_time,optional"`    //开始时间
	ETime    int64  `json:"e_time,optional"`    //结束时间
	Name     string `json:"name,optional"`      //模糊查询
	UAddress string `json:"u_address,optional"` //用户地址
}

type AdminAiComputingOrderListItem struct {
	Id                 int64   `json:"id"`
	Name               string  `json:"name"`                 //项目名字
	Amount             float64 `json:"amount"`               //投资额度
	ComputingPowerUnit string  `json:"computing_power_unit"` //算力单位
	ServiceMonth       int64   `json:"service_month"`        //服务周期
	LeftDay            int64   `json:"left_day"`             //剩余回报时间
	SendAmount         float64 `json:"send_amount"`
	CreatedAt          int64   `json:"created_at"`
}

type AdminAiComputingOrderListResp struct {
	List     []AdminAiComputingOrderListItem `json:"list"`
	Page     int32                           `json:"page"`      // 页码
	PageSize int32                           `json:"page_size"` // 每页数量
	Total    int64                           `json:"total"`     // 总数
}

type AddOrUpdateAiComputingReq struct {
	Id                  int64   `json:"id,optional"` //项目ID
	Name                string  `json:"name"`        //项目名字
	Price               float64 `json:"price"`       //价格
	Icon                string  `json:"icon"`
	Content             string  `json:"content,optional"`      //描述
	ServiceMonth        int32   `json:"service_month"`         //服务周期
	ComputingPowerUnit  string  `json:"computing_power_unit"`  //算力单位
	ComputingPowerValue int64   `json:"computing_power_value"` //算力数
	Status              int32   `json:"status"`                // 1-上架 2-下架
	IsDeleted           int     `json:"is_deleted,optional"`   // 1-删除
}

type AddOrUpdateAiComputingResp struct {
}

type DropAiComputingApplyReq struct {
	Id     int64   `json:"id"`     //申请记录ID
	Amount float64 `json:"amount"` //发放金额
}

type DropAiComputingApplyResp struct {
}

type DropAiComputingApplyListReq struct {
	Id       int64 `json:"id"`        //订单ID
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
}

type DropAiComputingApplyListItem struct {
	UAddress  string  `json:"u_address"`  //申请地址
	Amount    float64 `json:"amount"`     //申请数量
	CreatedAt int64   `json:"created_at"` //申请时间
}

type DropAiComputingApplyListResp struct {
	List     []DropAiComputingApplyListItem `json:"list"`
	Page     int32                          `json:"page"`      // 页码
	PageSize int32                          `json:"page_size"` // 每页数量
	Total    int64                          `json:"total"`     // 总数
}

type GetAiComputingListItem struct {
	Id                  int64   `json:"id"`    //项目ID
	Name                string  `json:"name"`  //项目名字
	Price               float64 `json:"price"` //价格
	Icon                string  `json:"icon"`
	Content             string  `json:"content"`               //描述
	ServiceMonth        int64   `json:"service_month"`         //有效期
	ComputingPowerUnit  string  `json:"computing_power_unit"`  //算力单位
	ComputingPowerValue int64   `json:"computing_power_value"` //算力值
}

type GetAiComputingListReq struct {
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
}

type GetAiComputingListResp struct {
	List     []GetAiComputingListItem `json:"list"`
	Page     int32                    `json:"page"`      // 页码
	PageSize int32                    `json:"page_size"` // 每页数量
	Total    int64                    `json:"total"`     // 总数
}

type BuyAiComputingReq struct {
	Id int64 `json:"id"`
}

type BuyAiComputingResp struct {
	OrderId   int64   `json:"order_id"`
	Amount    float64 `json:"Amount"`
	Sign      string  `json:"sign"`
	CreatedAt int64   `json:"created_at"`
}

type AiComputingOrderListReq struct {
	Page     int32 `json:"page"`      // 页码
	PageSize int32 `json:"page_size"` // 每页数量
}

type AiComputingOrderListItem struct {
	Id                 int64   `json:"id"`
	Name               string  `json:"name"`                 //项目名字
	Amount             float64 `json:"amount"`               //投资额度
	ComputingPowerUnit string  `json:"computing_power_unit"` //算力单位
	ServiceMonth       int64   `json:"service_month"`        //服务周期
	LeftDay            int64   `json:"left_day"`             //剩余回报时间
	WithdrawAmount     float64 `json:"withdraw_amount"`      //可提现
	CreatedAt          int64   `json:"created_at"`
}

type AiComputingOrderListResp struct {
	List     []AiComputingOrderListItem `json:"list"`
	Page     int32                      `json:"page"`      // 页码
	PageSize int32                      `json:"page_size"` // 每页数量
	Total    int64                      `json:"total"`     // 总数
}

type ApplyAiComputingReq struct {
	Id      int64  `json:"id"`      //订单ID
	Address string `json:"address"` //地址
}

type ApplyAiComputingResp struct {
}
