// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adminPackageProject "air-drop/cmd/internal/handler/admin/PackageProject"
	adminai_computing "air-drop/cmd/internal/handler/admin/ai_computing"
	adminlinkproject "air-drop/cmd/internal/handler/admin/linkproject"
	adminorder "air-drop/cmd/internal/handler/admin/order"
	adminproject "air-drop/cmd/internal/handler/admin/project"
	adminsetting "air-drop/cmd/internal/handler/admin/setting"
	adminuser "air-drop/cmd/internal/handler/admin/user"
	ai_computing "air-drop/cmd/internal/handler/ai_computing"
	link_project "air-drop/cmd/internal/handler/link_project"
	order "air-drop/cmd/internal/handler/order"
	package_project "air-drop/cmd/internal/handler/package_project"
	person "air-drop/cmd/internal/handler/person"
	"air-drop/cmd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swg",
				Handler: swgHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getNonce",
				Handler: person.NonceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: person.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminLogin",
				Handler: person.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/person"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/personInfo",
				Handler: person.PersonInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inviteCode/input",
				Handler: person.InviteCodeInputHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inviteCode/changeSelf",
				Handler: person.InviteCodeChangeSelfHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inviteList",
				Handler: person.InviteListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/walletLogList",
				Handler: person.WalletLogListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/person"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getPackageProjectList",
				Handler: package_project.GetPackageProjectListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/buyPackageProject",
				Handler: package_project.BuyPackageProjectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/packageProject"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getLinkProjectList",
				Handler: link_project.GetLinkProjectListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/buyPackageProject",
				Handler: link_project.BuyLinkProjectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/linkProject"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getOrderInfo",
				Handler: order.GetOrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getPackageOrderList",
				Handler: order.GetPackageOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getLinkOrderList",
				Handler: order.GetLinkOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/applyLinkEarnings",
				Handler: order.ApplyLinkEarningsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getApplyLinkLogList",
				Handler: order.GetApplyLinkEarningsListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getLinkProjectList",
				Handler: adminlinkproject.GetLinkProjectListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addOrUpdateLinkProjectList",
				Handler: adminlinkproject.AddOrUpdateLinkProjectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/linkproject"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getLinkProjectOrderList",
				Handler: adminorder.GetLinkProjectOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getPackageProjectOrderList",
				Handler: adminorder.GetPackageProjectOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dropLinkApplyLinkProject",
				Handler: adminorder.DropLinkApplyLinkProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dropApplyPackageProject",
				Handler: adminorder.DropApplyPackageProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dropApplyPackageListProject",
				Handler: adminorder.DropApplyPackageListProjectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getPackageProjectList",
				Handler: adminPackageProject.GetPackageProjectListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addOrUpdatePackageProjectList",
				Handler: adminPackageProject.AddOrUpdatePackageProjectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/packageProject"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getProjectList",
				Handler: adminproject.GetProjectListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addOrUpdateProjectList",
				Handler: adminproject.AddOrUpdateProjectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/project"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getSettingList",
				Handler: adminsetting.GetSettingListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getSettingKey",
				Handler: adminsetting.GetSettingKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/setSettingKey",
				Handler: adminsetting.SetSettingKeyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/setting"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getUserList",
				Handler: adminuser.GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/walletLogList",
				Handler: adminuser.WalletLogListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addOrUpdateAiComputing",
				Handler: adminai_computing.AddOrUpdateAiComputingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminGetAiComputingList",
				Handler: adminai_computing.AdminGetAiComputingListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/aiComputingOrderList",
				Handler: adminai_computing.AiComputingOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dropAiComputingApply",
				Handler: adminai_computing.DropAiComputingApplyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dropAiComputingApplyList",
				Handler: adminai_computing.DropAiComputingApplyListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/admin/aiComputing"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getAiComputingList",
				Handler: ai_computing.GetAiComputingListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/buyAiComputing",
				Handler: ai_computing.BuyAiComputingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/aiComputingOrderList",
				Handler: ai_computing.AiComputingOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/applyAiComputing",
				Handler: ai_computing.ApplyAiComputingHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/aiComputing"),
	)
}
